name: Build W3UnicodeSaveFix

on:
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PS2EXE
        shell: powershell
        run: |
          Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
          Install-Module ps2exe -Scope CurrentUser -Force -AllowClobber

      - name: Build EXE
        shell: powershell
        run: |
          Invoke-ps2exe `
            -InputFile .\W3UnicodeSaveFix.ps1 `
            -OutputFile .\W3UnicodeSaveFix.exe `
            -NoConsole `
            -Title "W3UnicodeSaveFix"

      - name: Verify File Exists
        shell: powershell
        run: |
          Get-ChildItem -Path .\W3UnicodeSaveFix.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: W3UnicodeSaveFix
          path: ${{ github.workspace }}/W3UnicodeSaveFix.exe
